import { Geist, Geist_Mono, Righteous, Playwrite_AU_SA, Covered_By_Your_Grace } from 'next/font/google';
import { ThemeProvider } from '@/components/app-carousel/theme-provider';

import './globals.css';
import { AppHead } from '@/components/app-carousel/head';
import { Footer } from '@/components/app-carousel/footer';
import { Toaster } from '@/components/ui/toaster';

import type { Metadata } from 'next';

const playIE = Playwrite_AU_SA({
  variable: '--font-playwrite_ie',
});

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const righteous = Righteous({
  weight: '400',
  variable: '--font-righteous',
  subsets: ['latin'],
});

const coverfont = Covered_By_Your_Grace({
  weight: '400',
  variable: '--font-cover',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'archie web',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${playIE.variable}
          ${righteous.variable}
          ${coverfont.variable}
          select-none antialiased
        `}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex w-svw flex-1 flex-col">
            <div className="flex min-h-svh flex-col">
              <AppHead />
              {children}
              <Toaster />
            </div>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
